apiVersion: apps/v1
kind: Deployment
metadata:
  name: UdacityCapstone
  labels:
    app: UdacityCapstone
    
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: UdacityCapstone
  template:
    metadata:
      labels:
        app: UdacityCapstone
        
    spec:
      containers:
      - name: UdacityCapstone
        image: oluseyi01/UdacityCapstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: UdacityCapstone-lb
  labels:
    app: UdacityCapstone
    
spec:
  selector:
    app: UdacityCapstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer