# Python CircleCI 2.0 configuration file
# 
# Check https://circleci.com/docs/2.0/language-python/ for more details
# 

version: 2.1
  
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
      
    working_directory: ~/Capstone
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
                

  test_lint:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: python:3.7.3-stretch
      
    working_directory: ~/Capstone
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
            # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            make lint
   docker_build:
    docker:
      - image: circleci/golang:1.15
        auth:
             username: $DOCKER_USERNAME
             password: $DOCKER_PASSWORD
    steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Push image to a docker repository
                  command: |
                          docker build --tag=UdacityCapstone .
                          docker image ls
                          dockerpath=oluseyi01/UdacityCapstone
                          echo "Docker ID and Image: $dockerpath"
                          docker login -u oluseyi01 -p $DOCKER_PASSWORD &&\
                                    docker tag UdacityCapstone $dockerpath
                          docker push $dockerpath
  Infrastructure_and_Deployment:
    docker:
      - image: amazon/aws-cli
      
    working_directory: ~/Capstone
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run: 
          name: Install kubectl
          command: |
            yum install -y wget
            wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl
      
      - run:
          name: Connect cluster
          command: |
            aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $CLUSTER_NAME 
            kubectl get svc
      - run:
          name: Deploy cluster and update image
          command: |
            kubectl apply -f deploy.yml 
            kubectl get svc
            kubectl get pods
            
      - run:
          name: rollout deployment 
          command: |
            kubectl rollout status deployment.apps/capstone-deploy
            kubectl get all
  
  
workflows:
  my_workflow:
    jobs:
      - build
      - test_lint:
          requires: [build]
      - docker_build:
          requires: [test_lint]
      #- Infrastructure_and_Deployment:
       #   requires: [docker_build]