# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2.1
orbs:
  docker: circleci/docker@1.6.0
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.12.0
  
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
      
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
                

  test_lint:
    docker:
      - image: python:3.7.3-stretch
      
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
            # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
            make lint
  build-and-push-docker-image:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build --tag=oluseyi01/udacitycapstone .
            docker image ls
            docker login -u oluseyi01 -p $DOCKER_PASSWORD
            docker push oluseyi01/udacitycapstone
  
  #Deploy_to_kube:
    #docker:
      - image: amazon/aws-cli
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      
      - run: 
          name: Install kubectl
          command: |
            yum install -y wget
            wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl
      
      - run:
          name: Connect cluster
          command: |
            aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $CLUSTER_NAME 
            kubectl get svc
      - run:
          name: Deploy cluster and update image
          command: |
            kubectl apply -f mydeployment.yml 
            kubectl get svc
            kubectl get pods
            
      - run:
          name: rollout deployment 
          command: |
            kubectl rollout status deployment.apps/capstone-deploy
            kubectl get all          

workflows:
  my_workflow:
    jobs:
      - build
      - test_lint:
          requires: [build]
      #- build-and-push-docker-image:
          #requires: [test_lint]            
      #- Deploy_to_kube:
          #requires: [build-and-push-docker-image]
